# Generated by Django 5.0.1 on 2024-02-12 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_comment_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='posted_by',
            field=models.CharField(default=0.009009009009009009, max_length=200),
            preserve_default=False,
        ),
    ]
