# Generated by Django 5.0.1 on 2025-05-13 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, default='static/images/download.png', upload_to='users/%Y/%m/%d'),
        ),
    ]
